#ifndef VIDEOPLAYERLIB_EXPORT_H
#define VIDEOPLAYERLIB_EXPORT_H

#if defined(BUILD_VIDEO_LIBRARY)
#	define VIDEO_LIB_EXPORT Q_DECL_EXPORT
#else
#	define VIDEO_LIB_EXPORT Q_DECL_IMPORT
#endif

#endif	// VIDEOPLAYERLIB_EXPORT_H
