#DESTDIR = $$PWD/windows
DESTDIR = $$CORE_BUILDS_LIBRARIES_PATH
LIBS += -L$$CORE_ROOT_DIR/Common/3dParty/cef/$$CORE_BUILDS_PLATFORM_PREFIX/build -llibcef
LIBS += -L$$CORE_BUILDS_LIBRARIES_PATH -lgraphics -llibxml -lOfficeUtils -lUnicodeConverter

SRC_PATH = $$PWD/../../ChromiumBasedEditors/lib/src/cef/windows

################### CEF ##################
INCLUDEPATH += \
    $$SRC_PATH

DEFINES += \
    "V8_DEPRECATION_WARNINGS" \
    "_WIN32_WINNT=0x0602" \
    "WINVER=0x0602" \
    "WIN32" \
    "_WINDOWS" \
    "NOMINMAX" \
    "PSAPI_VERSION=1" \
    "_CRT_RAND_S" \
    "CERT_CHAIN_PARA_HAS_EXTRA_FIELDS" \
    "WIN32_LEAN_AND_MEAN" \
    "_ATL_NO_OPENGL" \
    "_HAS_EXCEPTIONS=0" \
    "_SECURE_ATL" \
    "CHROMIUM_BUILD" \
    "TOOLKIT_VIEWS=1" \
    "USE_AURA=1" \
    "USE_ASH=1" \
    "USE_DEFAULT_RENDER_THEME=1" \
    "USE_LIBJPEG_TURBO=1" \
    "ENABLE_ONE_CLICK_SIGNIN" \
    "ENABLE_PRE_SYNC_BACKUP" \
    "ENABLE_REMOTING=1" \
    "ENABLE_WEBRTC=1" \
    "ENABLE_PEPPER_CDMS" \
    "ENABLE_CONFIGURATION_POLICY" \
    "ENABLE_NOTIFICATIONS" \
    "ENABLE_HIDPI=1" \
    "ENABLE_EGLIMAGE=1" \
    "__STD_C" \
    "_CRT_SECURE_NO_DEPRECATE" \
    "_SCL_SECURE_NO_DEPRECATE" \
    "NTDDI_VERSION=0x06020000" \
    "_USING_V110_SDK71_" \
    "ENABLE_TASK_MANAGER=1" \
    "ENABLE_EXTENSIONS=1" \
    "ENABLE_PLUGIN_INSTALLATION=1" \
    "ENABLE_PLUGINS=1" \
    "ENABLE_SESSION_SERVICE=1" \
    "ENABLE_THEMES=1" \
    "ENABLE_AUTOFILL_DIALOG=1" \
    "ENABLE_BACKGROUND=1" \
    "ENABLE_GOOGLE_NOW=1" \
    "CLD_VERSION=2" \
    "CLD2_DATA_SOURCE=static" \
    "ENABLE_FULL_PRINTING=1" \
    "ENABLE_PRINTING=1" \
    "ENABLE_SPELLCHECK=1" \
    "ENABLE_CAPTIVE_PORTAL_DETECTION=1" \
    "ENABLE_APP_LIST=1" \
    "ENABLE_SETTINGS_APP=1" \
    "ENABLE_MANAGED_USERS=1" \
    "ENABLE_MDNS=1" \
    "ENABLE_SERVICE_DISCOVERY=1" \
    "ENABLE_WIFI_BOOTSTRAPPING=1" \
    "ENABLE_LOAD_COMPLETION_HACKS=1" \
    "USING_CEF_SHARED" \
    "__STDC_CONSTANT_MACROS" \
    "__STDC_FORMAT_MACROS" \
    "NDEBUG" \
    "NVALGRIND" \
    "DYNAMIC_ANNOTATIONS_ENABLED=0"

LIBS += -lwininet \
        -ldnsapi \
        -lversion \
        -lmsimg32 \
        -lws2_32 \
        -lusp10 \
        -lpsapi \
        -ldbghelp \
        -lwinmm \
        -lshlwapi \
        -lkernel32 \
        -lgdi32 \
        -lwinspool \
        -lcomdlg32 \
        -ladvapi32 \
        -lshell32 \
        -lole32 \
        -loleaut32 \
        -luser32 \
        -luuid \
        -lodbc32 \
        -lodbccp32 \
        -ldelayimp \
        -lcredui \
        -lnetapi32 \
        -lcomctl32 \
        -lrpcrt4 \
        -lgdiplus \
        -lUrlmon \
        -lOpenGL32

INCLUDEPATH += \
    src/cef/windows

HEADERS += \
    $$SRC_PATH/cefclient/browser/binding_test.h \
    $$SRC_PATH/cefclient/browser/browser_window.h \
    $$SRC_PATH/cefclient/browser/browser_window_osr_win.h \
    $$SRC_PATH/cefclient/browser/browser_window_std_win.h \
    $$SRC_PATH/cefclient/browser/bytes_write_handler.h \
    $$SRC_PATH/cefclient/browser/client_app_browser.h \
    $$SRC_PATH/cefclient/browser/client_handler.h \
    $$SRC_PATH/cefclient/browser/client_handler_osr.h \
    $$SRC_PATH/cefclient/browser/client_handler_std.h \
    $$SRC_PATH/cefclient/browser/client_types.h \
    $$SRC_PATH/cefclient/browser/dialog_test.h \
    $$SRC_PATH/cefclient/browser/geometry_util.h \
    $$SRC_PATH/cefclient/browser/main_context.h \
    $$SRC_PATH/cefclient/browser/main_context_impl.h \
    $$SRC_PATH/cefclient/browser/main_message_loop.h \
    $$SRC_PATH/cefclient/browser/main_message_loop_multithreaded_win.h \
    $$SRC_PATH/cefclient/browser/main_message_loop_std.h \
    $$SRC_PATH/cefclient/browser/osr_dragdrop_events.h \
    $$SRC_PATH/cefclient/browser/osr_dragdrop_win.h \
    $$SRC_PATH/cefclient/browser/osr_renderer.h \
    $$SRC_PATH/cefclient/browser/osr_window_win.h \
    $$SRC_PATH/cefclient/browser/preferences_test.h \
    $$SRC_PATH/cefclient/browser/resource.h \
    $$SRC_PATH/cefclient/browser/resource_util.h \
    $$SRC_PATH/cefclient/browser/response_filter_test.h \
    $$SRC_PATH/cefclient/browser/root_window.h \
    $$SRC_PATH/cefclient/browser/root_window_manager.h \
    $$SRC_PATH/cefclient/browser/root_window_win.h \
    $$SRC_PATH/cefclient/browser/scheme_test.h \
    $$SRC_PATH/cefclient/browser/temp_window.h \
    $$SRC_PATH/cefclient/browser/temp_window_win.h \
    $$SRC_PATH/cefclient/browser/test_runner.h \
    $$SRC_PATH/cefclient/browser/urlrequest_test.h \
    $$SRC_PATH/cefclient/browser/util_win.h \
    $$SRC_PATH/cefclient/browser/window_test.h \
    $$SRC_PATH/cefclient/common/client_app.h \
    $$SRC_PATH/cefclient/common/client_app_other.h \
    $$SRC_PATH/cefclient/common/client_switches.h \
    $$SRC_PATH/cefclient/common/scheme_test_common.h \
    $$SRC_PATH/cefclient/renderer/client_app_renderer.h \
    $$SRC_PATH/cefclient/renderer/client_renderer.h \
    $$SRC_PATH/cefclient/renderer/performance_test.h \
    $$SRC_PATH/cefclient/renderer/performance_test_setup.h \
    $$SRC_PATH/include/base/internal/cef_atomicops_x86_msvc.h \
    $$SRC_PATH/include/base/internal/cef_bind_internal.h \
    $$SRC_PATH/include/base/internal/cef_bind_internal_win.h \
    $$SRC_PATH/include/base/internal/cef_callback_internal.h \
    $$SRC_PATH/include/base/internal/cef_lock_impl.h \
    $$SRC_PATH/include/base/internal/cef_raw_scoped_refptr_mismatch_checker.h \
    $$SRC_PATH/include/base/internal/cef_thread_checker_impl.h \
    $$SRC_PATH/include/base/cef_atomic_ref_count.h \
    $$SRC_PATH/include/base/cef_atomicops.h \
    $$SRC_PATH/include/base/cef_basictypes.h \
    $$SRC_PATH/include/base/cef_bind.h \
    $$SRC_PATH/include/base/cef_bind_helpers.h \
    $$SRC_PATH/include/base/cef_build.h \
    $$SRC_PATH/include/base/cef_callback.h \
    $$SRC_PATH/include/base/cef_callback_forward.h \
    $$SRC_PATH/include/base/cef_callback_helpers.h \
    $$SRC_PATH/include/base/cef_callback_list.h \
    $$SRC_PATH/include/base/cef_cancelable_callback.h \
    $$SRC_PATH/include/base/cef_lock.h \
    $$SRC_PATH/include/base/cef_logging.h \
    $$SRC_PATH/include/base/cef_macros.h \
    $$SRC_PATH/include/base/cef_move.h \
    $$SRC_PATH/include/base/cef_platform_thread.h \
    $$SRC_PATH/include/base/cef_ref_counted.h \
    $$SRC_PATH/include/base/cef_scoped_ptr.h \
    $$SRC_PATH/include/base/cef_string16.h \
    $$SRC_PATH/include/base/cef_template_util.h \
    $$SRC_PATH/include/base/cef_thread_checker.h \
    $$SRC_PATH/include/base/cef_thread_collision_warner.h \
    $$SRC_PATH/include/base/cef_trace_event.h \
    $$SRC_PATH/include/base/cef_tuple.h \
    $$SRC_PATH/include/base/cef_weak_ptr.h \
    $$SRC_PATH/include/capi/cef_app_capi.h \
    $$SRC_PATH/include/capi/cef_auth_callback_capi.h \
    $$SRC_PATH/include/capi/cef_base_capi.h \
    $$SRC_PATH/include/capi/cef_browser_capi.h \
    $$SRC_PATH/include/capi/cef_browser_process_handler_capi.h \
    $$SRC_PATH/include/capi/cef_callback_capi.h \
    $$SRC_PATH/include/capi/cef_client_capi.h \
    $$SRC_PATH/include/capi/cef_command_line_capi.h \
    $$SRC_PATH/include/capi/cef_context_menu_handler_capi.h \
    $$SRC_PATH/include/capi/cef_cookie_capi.h \
    $$SRC_PATH/include/capi/cef_dialog_handler_capi.h \
    $$SRC_PATH/include/capi/cef_display_handler_capi.h \
    $$SRC_PATH/include/capi/cef_dom_capi.h \
    $$SRC_PATH/include/capi/cef_download_handler_capi.h \
    $$SRC_PATH/include/capi/cef_download_item_capi.h \
    $$SRC_PATH/include/capi/cef_drag_data_capi.h \
    $$SRC_PATH/include/capi/cef_drag_handler_capi.h \
    $$SRC_PATH/include/capi/cef_find_handler_capi.h \
    $$SRC_PATH/include/capi/cef_focus_handler_capi.h \
    $$SRC_PATH/include/capi/cef_frame_capi.h \
    $$SRC_PATH/include/capi/cef_geolocation_capi.h \
    $$SRC_PATH/include/capi/cef_geolocation_handler_capi.h \
    $$SRC_PATH/include/capi/cef_jsdialog_handler_capi.h \
    $$SRC_PATH/include/capi/cef_keyboard_handler_capi.h \
    $$SRC_PATH/include/capi/cef_life_span_handler_capi.h \
    $$SRC_PATH/include/capi/cef_load_handler_capi.h \
    $$SRC_PATH/include/capi/cef_menu_model_capi.h \
    $$SRC_PATH/include/capi/cef_navigation_entry_capi.h \
    $$SRC_PATH/include/capi/cef_origin_whitelist_capi.h \
    $$SRC_PATH/include/capi/cef_parser_capi.h \
    $$SRC_PATH/include/capi/cef_path_util_capi.h \
    $$SRC_PATH/include/capi/cef_print_handler_capi.h \
    $$SRC_PATH/include/capi/cef_print_settings_capi.h \
    $$SRC_PATH/include/capi/cef_process_message_capi.h \
    $$SRC_PATH/include/capi/cef_process_util_capi.h \
    $$SRC_PATH/include/capi/cef_render_handler_capi.h \
    $$SRC_PATH/include/capi/cef_render_process_handler_capi.h \
    $$SRC_PATH/include/capi/cef_request_capi.h \
    $$SRC_PATH/include/capi/cef_request_context_capi.h \
    $$SRC_PATH/include/capi/cef_request_context_handler_capi.h \
    $$SRC_PATH/include/capi/cef_request_handler_capi.h \
    $$SRC_PATH/include/capi/cef_resource_bundle_capi.h \
    $$SRC_PATH/include/capi/cef_resource_bundle_handler_capi.h \
    $$SRC_PATH/include/capi/cef_resource_handler_capi.h \
    $$SRC_PATH/include/capi/cef_response_capi.h \
    $$SRC_PATH/include/capi/cef_response_filter_capi.h \
    $$SRC_PATH/include/capi/cef_scheme_capi.h \
    $$SRC_PATH/include/capi/cef_ssl_info_capi.h \
    $$SRC_PATH/include/capi/cef_stream_capi.h \
    $$SRC_PATH/include/capi/cef_string_visitor_capi.h \
    $$SRC_PATH/include/capi/cef_task_capi.h \
    $$SRC_PATH/include/capi/cef_trace_capi.h \
    $$SRC_PATH/include/capi/cef_urlrequest_capi.h \
    $$SRC_PATH/include/capi/cef_v8_capi.h \
    $$SRC_PATH/include/capi/cef_values_capi.h \
    $$SRC_PATH/include/capi/cef_web_plugin_capi.h \
    $$SRC_PATH/include/capi/cef_xml_reader_capi.h \
    $$SRC_PATH/include/capi/cef_zip_reader_capi.h \
    $$SRC_PATH/include/internal/cef_export.h \
    $$SRC_PATH/include/internal/cef_logging_internal.h \
    $$SRC_PATH/include/internal/cef_ptr.h \
    $$SRC_PATH/include/internal/cef_string.h \
    $$SRC_PATH/include/internal/cef_string_list.h \
    $$SRC_PATH/include/internal/cef_string_map.h \
    $$SRC_PATH/include/internal/cef_string_multimap.h \
    $$SRC_PATH/include/internal/cef_string_types.h \
    $$SRC_PATH/include/internal/cef_string_wrappers.h \
    $$SRC_PATH/include/internal/cef_thread_internal.h \
    $$SRC_PATH/include/internal/cef_time.h \
    $$SRC_PATH/include/internal/cef_trace_event_internal.h \
    $$SRC_PATH/include/internal/cef_types.h \
    $$SRC_PATH/include/internal/cef_types_win.h \
    $$SRC_PATH/include/internal/cef_types_wrappers.h \
    $$SRC_PATH/include/internal/cef_win.h \
    $$SRC_PATH/include/wrapper/cef_byte_read_handler.h \
    $$SRC_PATH/include/wrapper/cef_closure_task.h \
    $$SRC_PATH/include/wrapper/cef_helpers.h \
    $$SRC_PATH/include/wrapper/cef_message_router.h \
    $$SRC_PATH/include/wrapper/cef_resource_manager.h \
    $$SRC_PATH/include/wrapper/cef_stream_resource_handler.h \
    $$SRC_PATH/include/wrapper/cef_xml_object.h \
    $$SRC_PATH/include/wrapper/cef_zip_archive.h \
    $$SRC_PATH/include/cef_app.h \
    $$SRC_PATH/include/cef_auth_callback.h \
    $$SRC_PATH/include/cef_base.h \
    $$SRC_PATH/include/cef_browser.h \
    $$SRC_PATH/include/cef_browser_process_handler.h \
    $$SRC_PATH/include/cef_callback.h \
    $$SRC_PATH/include/cef_client.h \
    $$SRC_PATH/include/cef_command_line.h \
    $$SRC_PATH/include/cef_context_menu_handler.h \
    $$SRC_PATH/include/cef_cookie.h \
    $$SRC_PATH/include/cef_dialog_handler.h \
    $$SRC_PATH/include/cef_display_handler.h \
    $$SRC_PATH/include/cef_dom.h \
    $$SRC_PATH/include/cef_download_handler.h \
    $$SRC_PATH/include/cef_download_item.h \
    $$SRC_PATH/include/cef_drag_data.h \
    $$SRC_PATH/include/cef_drag_handler.h \
    $$SRC_PATH/include/cef_find_handler.h \
    $$SRC_PATH/include/cef_focus_handler.h \
    $$SRC_PATH/include/cef_frame.h \
    $$SRC_PATH/include/cef_geolocation.h \
    $$SRC_PATH/include/cef_geolocation_handler.h \
    $$SRC_PATH/include/cef_jsdialog_handler.h \
    $$SRC_PATH/include/cef_keyboard_handler.h \
    $$SRC_PATH/include/cef_life_span_handler.h \
    $$SRC_PATH/include/cef_load_handler.h \
    $$SRC_PATH/include/cef_menu_model.h \
    $$SRC_PATH/include/cef_navigation_entry.h \
    $$SRC_PATH/include/cef_origin_whitelist.h \
    $$SRC_PATH/include/cef_pack_resources.h \
    $$SRC_PATH/include/cef_pack_strings.h \
    $$SRC_PATH/include/cef_parser.h \
    $$SRC_PATH/include/cef_path_util.h \
    $$SRC_PATH/include/cef_print_handler.h \
    $$SRC_PATH/include/cef_print_settings.h \
    $$SRC_PATH/include/cef_process_message.h \
    $$SRC_PATH/include/cef_process_util.h \
    $$SRC_PATH/include/cef_render_handler.h \
    $$SRC_PATH/include/cef_render_process_handler.h \
    $$SRC_PATH/include/cef_request.h \
    $$SRC_PATH/include/cef_request_context.h \
    $$SRC_PATH/include/cef_request_context_handler.h \
    $$SRC_PATH/include/cef_request_handler.h \
    $$SRC_PATH/include/cef_resource_bundle.h \
    $$SRC_PATH/include/cef_resource_bundle_handler.h \
    $$SRC_PATH/include/cef_resource_handler.h \
    $$SRC_PATH/include/cef_response.h \
    $$SRC_PATH/include/cef_response_filter.h \
    $$SRC_PATH/include/cef_runnable.h \
    $$SRC_PATH/include/cef_sandbox_win.h \
    $$SRC_PATH/include/cef_scheme.h \
    $$SRC_PATH/include/cef_ssl_info.h \
    $$SRC_PATH/include/cef_stream.h \
    $$SRC_PATH/include/cef_string_visitor.h \
    $$SRC_PATH/include/cef_task.h \
    $$SRC_PATH/include/cef_trace.h \
    $$SRC_PATH/include/cef_urlrequest.h \
    $$SRC_PATH/include/cef_v8.h \
    $$SRC_PATH/include/cef_values.h \
    $$SRC_PATH/include/cef_version.h \
    $$SRC_PATH/include/cef_web_plugin.h \
    $$SRC_PATH/include/cef_xml_reader.h \
    $$SRC_PATH/include/cef_zip_reader.h \
    $$SRC_PATH/libcef_dll/cpptoc/app_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/base_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/browser_process_handler_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/client_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/completion_callback_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/context_menu_handler_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/cookie_visitor_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/delete_cookies_callback_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/dialog_handler_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/display_handler_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/domvisitor_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/download_handler_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/drag_handler_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/end_tracing_callback_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/find_handler_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/focus_handler_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/geolocation_handler_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/get_geolocation_callback_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/jsdialog_handler_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/keyboard_handler_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/life_span_handler_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/load_handler_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/navigation_entry_visitor_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/pdf_print_callback_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/print_handler_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/read_handler_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/render_handler_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/render_process_handler_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/request_context_handler_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/request_handler_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/resolve_callback_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/response_filter_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/resource_bundle_handler_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/resource_handler_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/run_file_dialog_callback_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/scheme_handler_factory_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/set_cookie_callback_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/string_visitor_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/task_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/urlrequest_client_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/v8accessor_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/v8handler_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/web_plugin_info_visitor_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/web_plugin_unstable_callback_cpptoc.h \
    $$SRC_PATH/libcef_dll/cpptoc/write_handler_cpptoc.h \
    $$SRC_PATH/libcef_dll/ctocpp/auth_callback_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/before_download_callback_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/binary_value_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/browser_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/browser_host_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/callback_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/command_line_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/context_menu_params_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/cookie_manager_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/dictionary_value_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/domdocument_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/domnode_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/download_item_callback_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/download_item_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/drag_data_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/file_dialog_callback_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/frame_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/geolocation_callback_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/jsdialog_callback_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/list_value_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/menu_model_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/navigation_entry_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/post_data_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/post_data_element_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/print_dialog_callback_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/print_job_callback_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/print_settings_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/process_message_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/request_callback_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/request_context_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/request_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/resource_bundle_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/response_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/run_context_menu_callback_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/scheme_registrar_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/sslcert_principal_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/sslinfo_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/stream_reader_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/stream_writer_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/task_runner_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/urlrequest_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/v8context_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/v8exception_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/v8stack_frame_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/v8stack_trace_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/v8value_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/value_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/web_plugin_info_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/xml_reader_ctocpp.h \
    $$SRC_PATH/libcef_dll/ctocpp/zip_reader_ctocpp.h \
    $$SRC_PATH/libcef_dll/wrapper/cef_browser_info_map.h \
    $$SRC_PATH/libcef_dll/transfer_util.h \
    $$SRC_PATH/libcef_dll/wrapper_types.h

SOURCES += \
    $$SRC_PATH/cefclient/browser/binding_test.cc \
    $$SRC_PATH/cefclient/browser/browser_window.cc \
    $$SRC_PATH/cefclient/browser/browser_window_osr_win.cc \
    #$$SRC_PATH/cefclient/browser/browser_window_std_win.cc \
    $$SRC_PATH/cefclient/browser/bytes_write_handler.cc \
    $$SRC_PATH/cefclient/browser/client_app_browser.cc \
    $$SRC_PATH/cefclient/browser/client_app_delegates_browser.cc \
    $$SRC_PATH/cefclient/browser/client_handler.cc \
    $$SRC_PATH/cefclient/browser/client_handler_osr.cc \
    $$SRC_PATH/cefclient/browser/client_handler_std.cc \
    $$SRC_PATH/cefclient/browser/dialog_test.cc \
    $$SRC_PATH/cefclient/browser/geometry_util.cc \
    $$SRC_PATH/cefclient/browser/main_context.cc \
    $$SRC_PATH/cefclient/browser/main_context_impl.cc \
    $$SRC_PATH/cefclient/browser/main_context_impl_win.cc \
    $$SRC_PATH/cefclient/browser/main_message_loop.cc \
    $$SRC_PATH/cefclient/browser/main_message_loop_multithreaded_win.cc \
    $$SRC_PATH/cefclient/browser/main_message_loop_std.cc \
    $$SRC_PATH/cefclient/browser/osr_dragdrop_win.cc \
    $$SRC_PATH/cefclient/browser/osr_renderer.cc \
    $$SRC_PATH/cefclient/browser/osr_window_win.cc \
    $$SRC_PATH/cefclient/browser/preferences_test.cc \
    $$SRC_PATH/cefclient/browser/resource_util_win.cc \
    $$SRC_PATH/cefclient/browser/response_filter_test.cc \
    $$SRC_PATH/cefclient/browser/root_window.cc \
    $$SRC_PATH/cefclient/browser/root_window_manager.cc \
    $$SRC_PATH/cefclient/browser/root_window_win.cc \
    $$SRC_PATH/cefclient/browser/scheme_test.cc \
    $$SRC_PATH/cefclient/browser/temp_window_win.cc \
    $$SRC_PATH/cefclient/browser/test_runner.cc \
    $$SRC_PATH/cefclient/browser/urlrequest_test.cc \
    $$SRC_PATH/cefclient/browser/util_win.cc \
    $$SRC_PATH/cefclient/browser/window_test.cc \
    $$SRC_PATH/cefclient/browser/window_test_win.cc \
    $$SRC_PATH/cefclient/common/client_app.cc \
    $$SRC_PATH/cefclient/common/client_app_delegates_common.cc \
    $$SRC_PATH/cefclient/common/client_app_other.cc \
    $$SRC_PATH/cefclient/common/client_switches.cc \
    $$SRC_PATH/cefclient/common/scheme_test_common.cc \
    $$SRC_PATH/cefclient/renderer/client_app_delegates_renderer.cc \
    $$SRC_PATH/cefclient/renderer/client_app_renderer.cc \
    $$SRC_PATH/cefclient/renderer/client_renderer.cc \
    $$SRC_PATH/cefclient/renderer/performance_test.cc \
    $$SRC_PATH/cefclient/renderer/performance_test_tests.cc \
    $$SRC_PATH/libcef_dll/base/cef_atomicops_x86_gcc.cc \
    $$SRC_PATH/libcef_dll/base/cef_bind_helpers.cc \
    $$SRC_PATH/libcef_dll/base/cef_callback_helpers.cc \
    $$SRC_PATH/libcef_dll/base/cef_callback_internal.cc \
    $$SRC_PATH/libcef_dll/base/cef_lock.cc \
    $$SRC_PATH/libcef_dll/base/cef_lock_impl.cc \
    $$SRC_PATH/libcef_dll/base/cef_logging.cc \
    $$SRC_PATH/libcef_dll/base/cef_ref_counted.cc \
    $$SRC_PATH/libcef_dll/base/cef_string16.cc \
    $$SRC_PATH/libcef_dll/base/cef_thread_checker_impl.cc \
    $$SRC_PATH/libcef_dll/base/cef_thread_collision_warner.cc \
    $$SRC_PATH/libcef_dll/base/cef_weak_ptr.cc \
    $$SRC_PATH/libcef_dll/cpptoc/app_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/base_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/browser_process_handler_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/client_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/completion_callback_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/context_menu_handler_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/cookie_visitor_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/delete_cookies_callback_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/dialog_handler_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/display_handler_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/domvisitor_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/download_handler_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/drag_handler_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/end_tracing_callback_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/find_handler_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/focus_handler_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/geolocation_handler_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/get_geolocation_callback_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/jsdialog_handler_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/keyboard_handler_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/life_span_handler_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/load_handler_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/navigation_entry_visitor_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/pdf_print_callback_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/print_handler_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/read_handler_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/render_handler_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/render_process_handler_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/request_context_handler_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/request_handler_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/resolve_callback_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/response_filter_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/resource_bundle_handler_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/resource_handler_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/run_file_dialog_callback_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/scheme_handler_factory_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/set_cookie_callback_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/string_visitor_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/task_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/urlrequest_client_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/v8accessor_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/v8handler_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/web_plugin_info_visitor_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/web_plugin_unstable_callback_cpptoc.cc \
    $$SRC_PATH/libcef_dll/cpptoc/write_handler_cpptoc.cc \
    $$SRC_PATH/libcef_dll/ctocpp/auth_callback_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/before_download_callback_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/binary_value_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/browser_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/browser_host_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/callback_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/command_line_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/context_menu_params_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/cookie_manager_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/dictionary_value_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/domdocument_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/domnode_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/download_item_callback_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/download_item_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/drag_data_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/file_dialog_callback_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/frame_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/geolocation_callback_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/jsdialog_callback_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/list_value_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/menu_model_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/navigation_entry_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/post_data_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/post_data_element_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/print_dialog_callback_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/print_job_callback_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/print_settings_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/process_message_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/request_callback_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/request_context_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/request_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/resource_bundle_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/response_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/run_context_menu_callback_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/scheme_registrar_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/sslcert_principal_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/sslinfo_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/stream_reader_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/stream_writer_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/task_runner_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/urlrequest_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/v8context_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/v8exception_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/v8stack_frame_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/v8stack_trace_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/v8value_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/value_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/web_plugin_info_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/xml_reader_ctocpp.cc \
    $$SRC_PATH/libcef_dll/ctocpp/zip_reader_ctocpp.cc \
    $$SRC_PATH/libcef_dll/wrapper/cef_byte_read_handler.cc \
    $$SRC_PATH/libcef_dll/wrapper/cef_closure_task.cc \
    $$SRC_PATH/libcef_dll/wrapper/cef_message_router.cc \
    $$SRC_PATH/libcef_dll/wrapper/cef_resource_manager.cc \
    $$SRC_PATH/libcef_dll/wrapper/cef_stream_resource_handler.cc \
    $$SRC_PATH/libcef_dll/wrapper/cef_xml_object.cc \
    $$SRC_PATH/libcef_dll/wrapper/cef_zip_archive.cc \
    $$SRC_PATH/libcef_dll/wrapper/libcef_dll_wrapper.cc \
    $$SRC_PATH/libcef_dll/wrapper/libcef_dll_wrapper2.cc \
    $$SRC_PATH/libcef_dll/transfer_util.cc

INCLUDEPATH += \
    ../../../core/DesktopEditor/agg-2.4/include \
    ../../../core/DesktopEditor/freetype-2.5.2/include

HEADERS += \
    $$PWD/src/clienthandler.h \
    $$PWD/src/client_app.h

SOURCES += \
    $$PWD/src/client_renderer_wrapper.cpp \
    $$PWD/src/main_windows.cpp
